-- Generated by `python -m app.db.dump_schema`. Do not edit by hand.

CREATE TYPE region AS ENUM ('Northeast', 'Midwest', 'South', 'West');

CREATE TYPE user_role AS ENUM ('student', 'parent', 'counselor', 'educator', 'admin');

CREATE TYPE college_control AS ENUM ('public', 'private');

CREATE TYPE comparison_kind AS ENUM ('college', 'major', 'career', 'city', 'scenario');

CREATE TYPE salary_subject AS ENUM ('career', 'major', 'college');

CREATE TYPE geography_level AS ENUM ('national', 'state', 'city');

CREATE TABLE careers (
	id VARCHAR(64) NOT NULL, 
	soc_code VARCHAR(10) NOT NULL, 
	title VARCHAR(160) NOT NULL, 
	category VARCHAR(60) NOT NULL, 
	education VARCHAR(60) NOT NULL, 
	automation_exposure SMALLINT NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (soc_code)
);

CREATE INDEX ix_careers_category ON careers (category);

CREATE TABLE data_sources (
	id VARCHAR(64) NOT NULL, 
	name VARCHAR(200) NOT NULL, 
	publisher VARCHAR(200) NOT NULL, 
	url TEXT NOT NULL, 
	dataset TEXT NOT NULL, 
	vintage VARCHAR(40) NOT NULL, 
	update_frequency VARCHAR(40) NOT NULL, 
	used_for TEXT NOT NULL, 
	methodology TEXT NOT NULL, 
	last_updated DATE NOT NULL, 
	PRIMARY KEY (id)
);

CREATE TABLE majors (
	id VARCHAR(64) NOT NULL, 
	name VARCHAR(120) NOT NULL, 
	category VARCHAR(60) NOT NULL, 
	cip_code VARCHAR(10) NOT NULL, 
	industries TEXT[] NOT NULL, 
	grad_school_rate FLOAT NOT NULL, 
	PRIMARY KEY (id)
);

CREATE INDEX ix_majors_category ON majors (category);

CREATE INDEX ix_majors_cip_code ON majors (cip_code);

CREATE TABLE research_projects (
	id VARCHAR(64) NOT NULL, 
	title VARCHAR(200) NOT NULL, 
	question TEXT NOT NULL, 
	methodology TEXT NOT NULL, 
	dataset TEXT NOT NULL, 
	findings TEXT, 
	limitations TEXT NOT NULL, 
	source_ids VARCHAR(64)[] NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	published_at TIMESTAMP WITH TIME ZONE, 
	PRIMARY KEY (id)
);

CREATE TABLE states (
	code VARCHAR(2) NOT NULL, 
	fips VARCHAR(2) NOT NULL, 
	name VARCHAR(64) NOT NULL, 
	region region NOT NULL, 
	state_income_tax_rate FLOAT NOT NULL, 
	public_tuition_in_state INTEGER NOT NULL, 
	rpp FLOAT NOT NULL, 
	wage_index FLOAT NOT NULL, 
	PRIMARY KEY (code), 
	UNIQUE (fips)
);

CREATE TABLE users (
	id UUID NOT NULL, 
	auth_subject VARCHAR(200) NOT NULL, 
	email VARCHAR(320) NOT NULL, 
	display_name VARCHAR(120), 
	role user_role NOT NULL, 
	profile JSONB NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (auth_subject), 
	UNIQUE (email)
);

CREATE TABLE cities (
	id VARCHAR(64) NOT NULL, 
	name VARCHAR(120) NOT NULL, 
	state_code VARCHAR(2) NOT NULL, 
	region region NOT NULL, 
	lat FLOAT NOT NULL, 
	lon FLOAT NOT NULL, 
	metro_population_m FLOAT NOT NULL, 
	local_income_tax_rate FLOAT NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(state_code) REFERENCES states (code)
);

CREATE INDEX ix_cities_state_code ON cities (state_code);

CREATE TABLE folders (
	id UUID NOT NULL, 
	user_id UUID NOT NULL, 
	name VARCHAR(120) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (user_id, name), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX ix_folders_user_id ON folders (user_id);

CREATE TABLE major_careers (
	major_id VARCHAR(64) NOT NULL, 
	career_id VARCHAR(64) NOT NULL, 
	major_rank SMALLINT, 
	career_rank SMALLINT, 
	PRIMARY KEY (major_id, career_id), 
	FOREIGN KEY(major_id) REFERENCES majors (id) ON DELETE CASCADE, 
	FOREIGN KEY(career_id) REFERENCES careers (id) ON DELETE CASCADE
);

CREATE INDEX ix_major_careers_career_id ON major_careers (career_id);

CREATE TABLE colleges (
	id VARCHAR(64) NOT NULL, 
	name VARCHAR(200) NOT NULL, 
	short_name VARCHAR(80) NOT NULL, 
	city_id VARCHAR(64) NOT NULL, 
	state_code VARCHAR(2) NOT NULL, 
	control college_control NOT NULL, 
	undergrad_size INTEGER NOT NULL, 
	acceptance_rate FLOAT, 
	grad_rate FLOAT NOT NULL, 
	retention_rate FLOAT NOT NULL, 
	lat FLOAT NOT NULL, 
	lon FLOAT NOT NULL, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_colleges_grad_rate CHECK (grad_rate BETWEEN 0 AND 1), 
	FOREIGN KEY(city_id) REFERENCES cities (id), 
	FOREIGN KEY(state_code) REFERENCES states (code)
);

CREATE INDEX ix_colleges_city_id ON colleges (city_id);

CREATE INDEX ix_colleges_state_control ON colleges (state_code, control);

CREATE TABLE employment_data (
	id SERIAL NOT NULL, 
	city_id VARCHAR(64), 
	state_code VARCHAR(2), 
	career_id VARCHAR(64), 
	major_id VARCHAR(64), 
	source_id VARCHAR(64) NOT NULL, 
	year SMALLINT NOT NULL, 
	unemployment_rate FLOAT, 
	underemployment_rate FLOAT, 
	youth_unemployment_rate FLOAT, 
	job_growth_pct FLOAT, 
	employment INTEGER, 
	annual_openings INTEGER, 
	mean_wage INTEGER, 
	wage_growth FLOAT, 
	median_household_income INTEGER, 
	median_rent INTEGER, 
	PRIMARY KEY (id), 
	FOREIGN KEY(city_id) REFERENCES cities (id) ON DELETE CASCADE, 
	FOREIGN KEY(state_code) REFERENCES states (code) ON DELETE CASCADE, 
	FOREIGN KEY(career_id) REFERENCES careers (id) ON DELETE CASCADE, 
	FOREIGN KEY(major_id) REFERENCES majors (id) ON DELETE CASCADE, 
	FOREIGN KEY(source_id) REFERENCES data_sources (id)
);

CREATE INDEX ix_employment_career ON employment_data (career_id, year);

CREATE INDEX ix_employment_city ON employment_data (city_id, year);

CREATE INDEX ix_employment_major ON employment_data (major_id, year);

CREATE INDEX ix_employment_state ON employment_data (state_code, year);

CREATE TABLE favorites (
	user_id UUID NOT NULL, 
	entity_type comparison_kind NOT NULL, 
	entity_id VARCHAR(64) NOT NULL, 
	folder_id UUID, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (user_id, entity_type, entity_id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	FOREIGN KEY(folder_id) REFERENCES folders (id) ON DELETE SET NULL
);

CREATE TABLE living_costs (
	id SERIAL NOT NULL, 
	city_id VARCHAR(64) NOT NULL, 
	source_id VARCHAR(64) NOT NULL, 
	year SMALLINT NOT NULL, 
	rpp FLOAT NOT NULL, 
	median_rent_1br INTEGER NOT NULL, 
	median_home_price INTEGER NOT NULL, 
	transport_monthly INTEGER NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (city_id, year, source_id), 
	FOREIGN KEY(city_id) REFERENCES cities (id) ON DELETE CASCADE, 
	FOREIGN KEY(source_id) REFERENCES data_sources (id)
);

CREATE TABLE saved_comparisons (
	id UUID NOT NULL, 
	user_id UUID, 
	folder_id UUID, 
	kind comparison_kind NOT NULL, 
	item_ids VARCHAR(64)[] NOT NULL, 
	lens JSONB NOT NULL, 
	share_slug VARCHAR(16), 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	FOREIGN KEY(folder_id) REFERENCES folders (id) ON DELETE SET NULL, 
	UNIQUE (share_slug)
);

CREATE INDEX ix_saved_comparisons_user_id ON saved_comparisons (user_id);

CREATE TABLE scenarios (
	id UUID NOT NULL, 
	user_id UUID, 
	folder_id UUID, 
	name VARCHAR(160) NOT NULL, 
	paths JSONB NOT NULL, 
	assumptions JSONB NOT NULL, 
	share_slug VARCHAR(16), 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE, 
	FOREIGN KEY(folder_id) REFERENCES folders (id) ON DELETE SET NULL, 
	UNIQUE (share_slug)
);

CREATE INDEX ix_scenarios_user_id ON scenarios (user_id);

CREATE TABLE college_costs (
	id SERIAL NOT NULL, 
	college_id VARCHAR(64) NOT NULL, 
	source_id VARCHAR(64) NOT NULL, 
	academic_year VARCHAR(9) NOT NULL, 
	tuition_in_state INTEGER NOT NULL, 
	tuition_out_of_state INTEGER NOT NULL, 
	cost_of_attendance INTEGER NOT NULL, 
	avg_net_price INTEGER NOT NULL, 
	pct_receiving_grants FLOAT NOT NULL, 
	avg_grant_aid INTEGER NOT NULL, 
	median_debt INTEGER NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (college_id, academic_year, source_id), 
	FOREIGN KEY(college_id) REFERENCES colleges (id) ON DELETE CASCADE, 
	FOREIGN KEY(source_id) REFERENCES data_sources (id)
);

CREATE TABLE salary_data (
	id SERIAL NOT NULL, 
	subject salary_subject NOT NULL, 
	career_id VARCHAR(64), 
	major_id VARCHAR(64), 
	college_id VARCHAR(64), 
	geography geography_level NOT NULL, 
	geography_code VARCHAR(64), 
	source_id VARCHAR(64) NOT NULL, 
	year SMALLINT NOT NULL, 
	p10 INTEGER, 
	p25 INTEGER, 
	median INTEGER, 
	p75 INTEGER, 
	p90 INTEGER, 
	early_career_median INTEGER, 
	mid_career_median INTEGER, 
	PRIMARY KEY (id), 
	CONSTRAINT ck_salary_one_subject CHECK ((career_id IS NOT NULL)::int + (major_id IS NOT NULL)::int + (college_id IS NOT NULL)::int = 1), 
	FOREIGN KEY(career_id) REFERENCES careers (id) ON DELETE CASCADE, 
	FOREIGN KEY(major_id) REFERENCES majors (id) ON DELETE CASCADE, 
	FOREIGN KEY(college_id) REFERENCES colleges (id) ON DELETE CASCADE, 
	FOREIGN KEY(source_id) REFERENCES data_sources (id)
);

CREATE INDEX ix_salary_career ON salary_data (career_id, geography, year);

CREATE INDEX ix_salary_college ON salary_data (college_id, year);

CREATE INDEX ix_salary_major ON salary_data (major_id, year);
