"""Write db/schema.sql from the SQLAlchemy models (PostgreSQL dialect).

    python -m app.db.dump_schema
"""

from pathlib import Path

from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateIndex, CreateTable

from .models import Base

OUT = Path(__file__).resolve().parents[2] / "db" / "schema.sql"


def render() -> str:
    dialect = postgresql.dialect()
    parts = ["-- Generated by `python -m app.db.dump_schema`. Do not edit by hand.\n"]
    enums = {}
    for table in Base.metadata.sorted_tables:
        for col in table.columns:
            t = col.type
            if getattr(t, "enums", None) and getattr(t, "name", None):
                enums[t.name] = t.enums
    for name, values in enums.items():
        vals = ", ".join(f"'{v}'" for v in values)
        parts.append(f"CREATE TYPE {name} AS ENUM ({vals});\n")
    for table in Base.metadata.sorted_tables:
        parts.append(str(CreateTable(table).compile(dialect=dialect)).strip() + ";\n")
        for index in sorted(table.indexes, key=lambda i: i.name or ""):
            parts.append(str(CreateIndex(index).compile(dialect=dialect)).strip() + ";\n")
    return "\n".join(parts)


if __name__ == "__main__":
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render())
    print(f"wrote {OUT}")
